"""empty message

Revision ID: 656bf18d7140
Revises: 8373ad588657
Create Date: 2023-10-31 14:55:43.415439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656bf18d7140'
down_revision = '8373ad588657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('users', 'password',
    existing_type=sa.VARCHAR(length=80),
    type_=sa.String(length=256),
    existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
